#!/bin/bash

DATA="../pokemon_data"
CSV_FILE="pokemon_report.csv"

echo "Name,Height (m),Weight (kg)" > "$CSV_FILE"

for FILE in "$DATA"/*.json; do
    NAME=$(jq -r '.name' "$FILE" | sed 's/.*/\u&/')
    HEIGHT=$(jq -r '.height' "$FILE" | awk '{ printf "%.2f", $1/10 }')
    WEIGHT=$(jq -r '.weight' "$FILE" | awk '{ printf "%.2f", $1/10 }')
    echo "$NAME,$HEIGHT,$WEIGHT" >> "$CSV_FILE"
done

echo -e "\n$(awk -F',' 'NR>1 { h+=$2; w+=$3; c++ } END { print "Average Height: " h/c " m\nAverage Weight: " w/c " kg" }' "$CSV_FILE")"
